version: '3.8'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of .NET: 3.1, 6.0
        VARIANT: "6.0"
    environment:
      - ConnectionStrings__EumelContext=Database=eumel;Host=db;Username=${DB_USER};Password=${DB_PASS}
      - ConnectionStrings__EumelIntegrationTestContext=Database=eumeltest;Host=db;Username=${DB_USER};Password=${DB_PASS}
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:14.3
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/pg-init-scripts:/docker-entrypoint-initdb.d

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_MULTIPLE_DATABASES=eumel,eumeltest
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  pgadmin:
    # todo add servers.json file
    image: dpage/pgadmin4
    ports: 
      - 127.0.0.1:5555:80
    # network_mode: service:db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres-data: null
